server:
  port: 9095
spring:
    application:
      name: report-service
    
eureka:
  client:
    instance:
      preferIpAddress: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
