eureka:
  client:
    instance:
      preferIpAddress: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8089
spring:
  application:
    name: BILLING-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Hari@7777
    url: jdbc:mysql://localhost:3306/billing
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
